#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_RELEASE = $(INC) -Ivstsdk2.4 -Ivstsdk2.4\vstgui.sf\vstgui -Ivstsdk2.4\public.sdk\source\vst2.x
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)-luuid -lole32 -lkernel32 -lgdi32 -luser32
LDFLAGS_RELEASE = $(LDFLAGS) -s -def vstsdk2.4\public.sdk\samples\vst2.x\win\vstplug.def
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\PingPongDelay.dll

OBJ_RELEASE = $(OBJDIR_RELEASE)\\Main.o $(OBJDIR_RELEASE)\\PingPongDelayEditor.o $(OBJDIR_RELEASE)\\PingPongDelayEffect.o $(OBJDIR_RELEASE)\\PingPongDelayUnit.o $(OBJDIR_RELEASE)\\Resources.o $(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x\\audioeffect.o $(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x\\audioeffectx.o $(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x\\vstplugmain.o $(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui\\aeffguieditor.o $(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui\\vstcontrols.o $(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui\\vstgui.o

all: release

clean: clean_release

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)
	cmd /c if not exist $(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x md $(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x
	cmd /c if not exist $(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui md $(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) -shared $(LIBDIR_RELEASE) $(OBJ_RELEASE)  -o $(OUT_RELEASE) $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\Main.o: Main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Main.cpp -o $(OBJDIR_RELEASE)\\Main.o

$(OBJDIR_RELEASE)\\PingPongDelayEditor.o: PingPongDelayEditor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c PingPongDelayEditor.cpp -o $(OBJDIR_RELEASE)\\PingPongDelayEditor.o

$(OBJDIR_RELEASE)\\PingPongDelayEffect.o: PingPongDelayEffect.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c PingPongDelayEffect.cpp -o $(OBJDIR_RELEASE)\\PingPongDelayEffect.o

$(OBJDIR_RELEASE)\\PingPongDelayUnit.o: PingPongDelayUnit.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c PingPongDelayUnit.cpp -o $(OBJDIR_RELEASE)\\PingPongDelayUnit.o

$(OBJDIR_RELEASE)\\Resources.o: Resources.rc
	$(WINDRES) -i Resources.rc -J rc -o $(OBJDIR_RELEASE)\\Resources.o -O coff $(INC_RELEASE)

$(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x\\audioeffect.o: vstsdk2.4\\public.sdk\\source\\vst2.x\\audioeffect.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c vstsdk2.4\\public.sdk\\source\\vst2.x\\audioeffect.cpp -o $(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x\\audioeffect.o

$(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x\\audioeffectx.o: vstsdk2.4\\public.sdk\\source\\vst2.x\\audioeffectx.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c vstsdk2.4\\public.sdk\\source\\vst2.x\\audioeffectx.cpp -o $(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x\\audioeffectx.o

$(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x\\vstplugmain.o: vstsdk2.4\\public.sdk\\source\\vst2.x\\vstplugmain.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c vstsdk2.4\\public.sdk\\source\\vst2.x\\vstplugmain.cpp -o $(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x\\vstplugmain.o

$(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui\\aeffguieditor.o: vstsdk2.4\\vstgui.sf\\vstgui\\aeffguieditor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c vstsdk2.4\\vstgui.sf\\vstgui\\aeffguieditor.cpp -o $(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui\\aeffguieditor.o

$(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui\\vstcontrols.o: vstsdk2.4\\vstgui.sf\\vstgui\\vstcontrols.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c vstsdk2.4\\vstgui.sf\\vstgui\\vstcontrols.cpp -o $(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui\\vstcontrols.o

$(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui\\vstgui.o: vstsdk2.4\\vstgui.sf\\vstgui\\vstgui.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c vstsdk2.4\\vstgui.sf\\vstgui\\vstgui.cpp -o $(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui\\vstgui.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)
	cmd /c rd $(OBJDIR_RELEASE)\\vstsdk2.4\\public.sdk\\source\\vst2.x
	cmd /c rd $(OBJDIR_RELEASE)\\vstsdk2.4\\vstgui.sf\\vstgui

.PHONY: before_release after_release clean_release

